import type { Metadata } from "next";
import Head from "next/head";

export const metadata: Metadata = {
  title: "Panel Administrativo",
  description: "Generated by create next app",
};

export const revalidate = 0;

export default function PanelAdministrativoLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="panel-administrativo-layout">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      {/* Aquí puedes agregar un header o navbar específico para el panel administrativo */}
      {children}
    </div>
  );
}